### ISSUE TITLE
<Post Headers & Question TOC> New Stack Exchange CSS bumps post bodies to the right

### ISSUE THREAD

**Issue by zcoop98** [samliew/SO-mod-userscripts#100]
**Describe the bug**
Script: Post Headers & Question TOC  
Apparently a new CSS change was pushed out by Stack last night across the network, which is causing the main `<div>` that holds question and answers content (`id="mainbar"`) on question pages to be pushed to the right, rendering immediately to the right of the *Asked*, *Active*, *Viewed* metadata row.

![Question is pushed right](https://user-images.githubusercontent.com/8434006/124937149-be106500-dfcc-11eb-9934-88db507ff42a.png)

This is very likely related to the changes described in a comment by Cody Gray on a recent Meta.SO post:

> This is because of a CSS change that just got pushed out, replacing the `grid--cell` class with `flex--item`. The problems you describe should repro on all browsers. A bunch of things broke with this change, most notably on the profile page. (Not to mention a bunch of userscripts that a number of us use to customize the site.) This change appears to have been little more than a global search-and-replace, with no testing whatsoever before it was deployed, as none of these side-effects were detected or fixed before it went live.

The three items in that question metadata row immediately below the title are indeed `class="flex--item ws-nowrap ..."` now:

![Metadata items now use the flex--item class](https://user-images.githubusercontent.com/8434006/124937509-1182b300-dfcd-11eb-831d-abf9f97fe737.png)

**To Reproduce**
1. Go to pretty much any post on the Stack Exchange Network with this userscript enabled
2. See error

**Expected behavior**
I expect posts to render in their normal place, with their left margin touching the left-sidebar.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.124

**Additional context**
It's possible that this issue doesn't occur on literally every post, but it definitely appears to occur on *most*, at least in what I've observed this morning.

**Comment by zcoop98** [comment]
Based on what I've seen over the last few days, this bug occurs when the width of the Asked/ Active/ Viewed row is less than a certain amount. 

As a workaround in the meantime, use this script in tandem with the [Roomba Forecaster userscript](https://github.com/makyen/StackExchange-userscripts/tree/master/Roomba-Forecaster), which adds an extra "Roomba" attribute to that metadata row, forcing the row to be long enough to bump post headers down into their proper location.

Roomba's added field:
![roomba data pushes](https://user-images.githubusercontent.com/8434006/125646653-9ad5534f-cabd-4e7a-a3b9-e8ff9e2e4625.png)

Before Roomba script:
![no roomba](https://user-images.githubusercontent.com/8434006/125646059-5c878f41-aef2-45cb-8640-1d04e058e711.png)

After Roomba script: 
![after roomba](https://user-images.githubusercontent.com/8434006/125646210-dba356f8-589e-4f30-92c6-6bd36f0f7011.png)

**Comment by samliew** [comment]
Fixed in #101, let me know if there are further issues.
