### ISSUE TITLE
StackExchangeDarkMode: Last commit made script stop working

### ISSUE THREAD

**Issue by Pikoh** [samliew/SO-mod-userscripts#115]
After last commit, SE pages don't show dark mode anymore. I reverted manually to the previous version (https://github.com/samliew/SO-mod-userscripts/blob/c15140325aed0b4916c18bccd376f33eb7cfabe4/StackExchangeDarkMode.user.js) and it's working again.

**Comment by samliew** [comment]
Sorry, this is now fixed!

8d5c1c6b8b49a41485c1524b6ef89f542973487b
