### ISSUE TITLE
Auto update the new activity bar

### ISSUE THREAD

**Issue by fredericomattos** [samliew/SO-mod-userscripts#139]
First I apologize if the option already exists and I haven't found it!

The search page pops up the box warning that it has new activities, is there an option to not need to click this button every time new activities exist? Additional: generate a more visible highlight of the questions that I have already opened.

What's the use? I want to keep up with the new questions that are asked, both to edit if there are errors and to answer when my knowledge allows.

**Comment by samliew** [comment]
What is this "new activity bar" that you are referring to?

**Comment by fredericomattos** [comment]
> What is this "new activity bar" that you are referring to?

Hi @samliew, i hope you are having a good wednesday, here it is (`1 question with new activity`):

![image](https://user-images.githubusercontent.com/58320500/176417942-d5416317-2038-4875-bd39-04f0924dad80.png)

**Comment by samliew** [comment]
Use [Advanced Search Helper](https://stackapps.com/questions/7971/9011) with auto-refresh.

You might also want to use [QuestionListsHelper](https://github.com/samliew/SO-mod-userscripts/blob/master/QuestionListsHelper.user.js) together with that.

**Comment by fredericomattos** [comment]
Thanks a lot @samliew !
