### ISSUE TITLE
Add a few additional patterns to CommentFlagsHelper to look for downvote comments

### ISSUE THREAD

**Issue by AWegnerGitHub** [samliew/SO-mod-userscripts#14]
**Is your feature request related to a problem? Please describe.**
Can orange highlighting be added to "downvote", "downvoter", "downvoted" (with and without spaces between "down" and "vote") and the "up-?voted?" pattern be modified to support the space as well. These are in CommentFlagsHelper.user.js

**Describe the solution you'd like**
I'd like these voting terms to be highlighted

**Additional context**
I'm not good at efficient regexes. I could copy the `up-?voted?` pattern, but I don't usually see the "downvoted" ones hyphenated, usually they are spaced. It may make sense to check for both a space or a hyphen though.

**Comment by samliew** [comment]
Test case attached

![screenshot_2018-11-26_111150](https://user-images.githubusercontent.com/845988/48987227-2dfdb400-f171-11e8-960e-d429766e5206.png)
