### ISSUE TITLE
Deleted Users Helper links to a wrong/non-existent user ending with numbers due to post-migration

### ISSUE THREAD

**Issue by andrew-tc** [samliew/SO-mod-userscripts#156]
**Describe the bug**
Deleted Users Helper links to a wrong/non-existent user ending with numbers due to post-migration

**To Reproduce**
1. Go to [this question](https://android.stackexchange.com/questions/249450/how-recover-photos-from-a-locked-android-smartphone) which was migrated from [here](https://superuser.com/questions/1755069/how-recover-photos-from-a-locked-android-smartphone)
2. At the time the user hasn't created the profile (see the screenshot below), clicking the username redirects to [a different, already existing user](https://android.stackexchange.com/users/38/jader-dias)

**Expected behavior**
Make it clear that the user is not deleted, but not yet existing due to migration?

**Screenshots**
![](https://i.stack.imgur.com/RlD0G.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 107

**Additional context**
None.

**Comment by samliew** [comment]
I don't think there is any way to differentiate a deleted and non-existent user, so we default it to deleted since it's more likely.
