### ISSUE TITLE
CHAT.CURRENT_ROOM_ID is not available on chat transcript pages

### ISSUE THREAD

**Issue by samliew** [samliew/SO-mod-userscripts#167]
**Describe the bug**
ChatImprovements: `CHAT.CURRENT_ROOM_ID` is not available on transcript pages.

https://github.com/samliew/SO-mod-userscripts/blob/03e6b97ea5613bf16025ecdc8bc9379c1a4339ca/ChatImprovements.user.js#L970

**To Reproduce**
1. Go to any chat transcript page
2. Try to search using the topbar
3. Search result does not include room ID

**Expected behavior**
Top bar search should only return results from transcript room's messages

**Screenshots**
![Screenshot_2023-01-25_181658](https://user-images.githubusercontent.com/845988/214537635-b6afc2b9-b6cd-49b5-bf5d-e12929b3da39.png)

**Comment by makyen** [comment]
IIRC, the place where I found the room ID on transcript pages was from the room info link's `href`. The selector for it is `'#sidebar-content .room-mini .room-mini-header .room-name a'` and `room = (/^(?:https?:)?(?:\/\/chat(?:\.meta)?\.stack(?:overflow|exchange)\.com)?\/rooms\/(\d+)/.exec(roomNameLink.href) || [false, false])[1];` I'd write it differently if I was doing it again, but it works, so I haven't touched it for quite a while.

**Comment by makyen** [comment]
Because the room ID isn't always available in the transcript URL (e.g. `https://chat.stackexchange.com/transcript/message/62846058`).
