### ISSUE TITLE
Can the reduce clutter script hide "Related question" under new questions?

### ISSUE THREAD

**Issue by daniel-white** [samliew/SO-mod-userscripts#169]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/735269/226726685-8b9dd0b1-dbf8-4e62-8347-b5b49f0a9c48.png">

This just showed up on a new question page for me today.

**Comment by samliew** [comment]
Already in my consideration.

Check out the lastest userscript I am working on at the moment: [SavedQuestionsHelper](https://github.com/samliew/SO-mod-userscripts/blob/master/SavedQuestionsHelper.user.js)

**Comment by samliew** [comment]
Done. Please update userscript to v3.0
