### ISSUE TITLE
CircuitLab simulate circuit links get intercepted by Lightbox Images

### ISSUE THREAD

**Issue by catija** [samliew/SO-mod-userscripts#174]
**Describe the bug**
Lightbox Images (which is super awesome and I recommend it all the time, by the way) seems to use the image URL as a way to identify what to convert into an image. Unfortunately, there's a tool on Electrical Engineering that actually creates schematic links using a stack.imgur image as part of the URL, which seems to cause Lightbox to try and render it as an image, which then fails with a "The requested content cannot be loaded. Please try again later." message. And, once the message is displayed, the X to close the image no longer works, so you have to refresh the page to make it clear (though I'm guessing that not trying to display the image will fix this?).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [a post on EE with a schematic. e.g.](https://electronics.stackexchange.com/questions/672600/transistor-switching/672648#672648) (with Lightbox Images enabled)
2. Click on "simulate this circuit" under one of the CircuitLab images

**Expected behaviour**
Instead of attempting to show an image, Lightbox should not try to display these links as images and clicking should actually take me to the CircuitLab viewer (https://www.circuitlab.com/editor/#?id=dstej3q4rw83). The link URLs look like this: `https://electronics.stackexchange.com/plugins/schematics?image=http%3a%2f%2fi.stack.imgur.com%2fAoB3Q.png` so maybe you can add an if statement to look for URLs that contain "plugins/schematics" or something like that?

**Screenshots**
![Screenshot 2023-08-07 at 8 37 26 AM](https://github.com/samliew/SO-mod-userscripts/assets/31834967/79dcb206-7fd4-4972-aefa-b193b88b007c)
![Screenshot 2023-08-07 at 8 37 38 AM](https://github.com/samliew/SO-mod-userscripts/assets/31834967/df7845ee-9198-4c01-a079-13cbbc5637e2)

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 
 - Browser: Chrome
 - Version 115.0.5790.170

**Additional context**

**Comment by samliew** [comment]
I assume such links will always end with `.png`. Done.
