### ISSUE TITLE
Lightbox Images script breaks close button on questions

### ISSUE THREAD

**Issue by DavidPostill** [samliew/SO-mod-userscripts#175]
**Describe the bug**
Lightbox Images 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any question
2. Click close button
3. Close dialog is not displayed
4. Disabling Lightbox Images 
5. Close dialog is displayed as expected.

**Expected behaviour**
Allow close dialog to display when Lightbox  is enabled

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [Firefox
 - Version 115.1 esr

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by samliew** [comment]
Thanks, fixed.
