### ISSUE TITLE
Add suspend button to mod flag queue

### ISSUE THREAD

**Issue by smileycreations15** [samliew/SO-mod-userscripts#18]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This script will add a suspend button near the post owner username in the mod flag review queue.

**Describe alternatives you've considered**
None

**Additional context**
When the button is clicked the moderator will be prompted for a suspension duration and the user will be suspended from the site for the selected duration.

cc: @samliew

**Comment by samliew** [comment]
**Suspension from site** (requires mod message and drops user to 1 rep), or just a **review suspension**?

If just a review suspension, use [User Review Ban Helper](https://github.com/samliew/SO-mod-userscripts#user-review-ban-helper-)

If require a mod message with suspension, use [Mod User Quicklinks Everywhere](https://github.com/samliew/SO-mod-userscripts#mod-user-quicklinks-everywhere-) to get to the user's mod page.

**Comment by smileycreations15** [comment]
@samliew User suspension from site but without going to the mod page.

**Comment by samliew** [comment]
@smileycreations15 and what mod message template to use? A suspension **requires** a mod message to be sent.

**Comment by smileycreations15** [comment]
@samliew  A message depending on the flag in the queue. A `abusive to others` message for rude or abusive flag, `plaigarism` for custom flags for plaigarism, `question repetition` for custom flags that indicate the question is asked more than 1 time on stackoverflow by the author, or custom mod message and a default suspension time.

**Comment by samliew** [comment]
As mod messages are non-retractable, I feel that they should be reviewed by the mods before manually sending off.

**Comment by smileycreations15** [comment]
A confirmation to the user can be displayed
