### ISSUE TITLE
What http request is used to set a tag moderator-only

### ISSUE THREAD

**Issue by smileycreations15** [samliew/SO-mod-userscripts#19]
How can I set a tag moderator-only with a http request?

**Comment by samliew** [comment]
What do you mean? Does this have anything to do with a particular userscript in this repo?

**Comment by smileycreations15** [comment]
Not about a userscript. This is about how can I set a tag moderator only with a http request.

**Comment by samliew** [comment]
Your comment makes no sense and doesn't seem to belong to this repo, so it should not be discussed here
