### ISSUE TITLE
Chat Emojis is making chat messages box bigger

### ISSUE THREAD

**Issue by double-beep** [samliew/SO-mod-userscripts#20]
**Describe the bug**
I think I have found a bug in the [ChatEmojis.user.js](https://github.com/samliew/SO-mod-userscripts/blob/master/ChatEmojis.user.js) userscript. It seems that it makes the chat message box bigger and so, new messages appear behind it and usernames are inside it when starting writing their name, e.g. start writing `@Sam` and the username (Samuel Liew) will appear inside the box.

**To Reproduce**
Just make sure that the userscript is installed and go to a random room. The bug will appear at the bottom of the page where the box exists.

**Expected behavior**
The box had to be as it was when the userscript was not active/installed; smaller.

**Screenshots**
How the box **is** (with a message above it):
[![](https://bit.ly/2VMqvds)](https://bit.ly/2VMqvds)

How it is when I am going to ping sombody:
[![](https://bit.ly/2UtOJce)](https://bit.ly/2UtOJce)

How it should be (with a message above it):
[![](https://bit.ly/2NSlUDY)](https://bit.ly/2NSlUDY)

How it should be when going to ping somebody:
[![](https://bit.ly/2NSmL7E)](https://bit.ly/2NSmL7E)

**Desktop (please complete the following information):**
 - OS: Windows 10, version 10.0.17763.316
 - Browser: Microsoft Edge
 - Version 44.17763.1.0

Userscript manager:
- Name: Tampermonkey
- Version: 4.8.5847

**I am not familiar** with JavaScript, so I don't know what is wrong here.

**Comment by double-beep** [comment]
Also, I don't know why the last update (~10 mins) to it was intended to fix, but my issue remains.

**Comment by samliew** [comment]
Thanks for reporting, let me know if the issue persists after updating

**Comment by double-beep** [comment]
@samliew no, issue gone, thank you very much; I can use it now.
