### ISSUE TITLE
Reduce Clutter reduces "edit tags" too much

### ISSUE THREAD

**Issue by cellio** [samliew/SO-mod-userscripts#21]
With the Reduce Clutter script enabled, this is what I see on questions now (screenshot is from Meta.SE):

![screenshot](https://user-images.githubusercontent.com/5557942/54401401-e5292700-469d-11e9-898a-00f070a96244.png)

The text is *very* light -- for me it's at the "what's that smudge?" point, where either darkening it or removing it would be better than leaving it as-is.

With the script disabled it looks like this:

![screenshot](https://user-images.githubusercontent.com/5557942/54401501-4e109f00-469e-11e9-8da3-152979be7cd7.png)

I'm hoping this was an unintended side effect of some other change.  I don't want to have to choose between "edit tags" being legible and having to see the comment icons all the time.

Thanks!

**Comment by samliew** [comment]
Thanks for the feedback, I'll increase the link's visibility

**Comment by samliew** [comment]
Bumped from 0.15 (15%) visibility to 0.5 (50%) when post is not focused
