### ISSUE TITLE
Deleted users helper: Text fields are too small on deleted users' pages on mobile

### ISSUE THREAD

**Issue by samliew** [samliew/SO-mod-userscripts#27]

**Comment by DavidPostill** [comment]
Problem is also apparent on desktops (Windows 7, Firefox 67.0.4:

![Screenshot - 09_07_2019 , 20_57_38](https://user-images.githubusercontent.com/7079224/60919083-beb27b80-a28c-11e9-935f-4e70d165a91c.png)

**Comment by samliew** [comment]
Figured out the issue, it's Firefox not playing nice with jQuery.
