### ISSUE TITLE
[Review Queue Helper] Allow users to toggle skip conditions 

### ISSUE THREAD

**Issue by Tyler-H** [samliew/SO-mod-userscripts#31]
Currently the Review Queue Helper script seems to auto skip questions where any of the following conditions are true (non-exhaustive):

- Question has multiple answers
- Question has accepted answer
- Review item is an audit

While I like skipping the last one (don't want to waste votes or risk getting dinged on a bad audit item, etc.), I *don't* want to skip on the first two occasions. I personally think it's more important to review those as they require corrective action (in either direction), which is more important/has more weight than an initial action.

Can we please have an option panel somewhere that allows us to choose each of the conditions where an item will be skipped? I like some of the features of this userscript but the current auto-skip criteria make the script unusable for me.

**Comment by samliew** [comment]
No longer skipping accepted questions by default, moved option to SOMU options (separate userscript needed).
