### ISSUE TITLE
Allow me to type an @ or # or $ when the review helper script is active

### ISSUE THREAD

**Issue by rschrieken** [samliew/SO-mod-userscripts#33]
**Describe the bug**
I tried to @-reply a user in a comment on a review. The @ is on top of the 2 on my keyboard layout. So I press shift, hit @ and instead of that key appearing in the comment I'm put in post edit mode, obviously because the script assumes I pressed the 2 key. 

**To Reproduce**
1. Go to a review
2. Click add comment
3. Press shift and '2'
4. Post is put in edit mode

**Expected behavior**
The character that is above the 2 is entered in the comment box

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169

**Additional context**
Was in Low Quality queue, in case it matters

**Comment by samliew** [comment]
Thanks, good catch!
