### ISSUE TITLE
Background is missing on SearchNavImprovements.user.js

### ISSUE THREAD

**Issue by a-stone-arachnid** [samliew/SO-mod-userscripts#4]
On Mac OS X 10.6.8, Firefox 45.9.0, there is no background on the main panel
![](https://user-images.githubusercontent.com/31635665/42735949-96484090-884c-11e8-8ac5-3b2d9a368405.png)

**Comment by samliew** [comment]
Thanks for reporting, can you verify if this issue is fixed?

**Comment by a-stone-arachnid** [comment]
Yes that works. Thanks.
