### ISSUE TITLE
[Review Queue Helper] Mod flag dialog autoclosing on single quote

### ISSUE THREAD

**Issue by tehphoenixz** [samliew/SO-mod-userscripts#40]
**Describe the bug**
When writing a custom mod flag on a post pressing the single quote key (') closes the flag dialog.

**To Reproduce**
1. Open any question.
2. Click the flag button to open the flag dialog and choose "in need of moderator intervention".
3. Enter a single quote (this can be on it's own or as part of a full message).
4. Flag dialog closes.

**Expected behavior**
The flag dialog doesn't close and the ' appears in the message

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Google Chrome
 - Version: Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by samliew** [comment]
Unable to repro single quote closing the flag dialog when custom flag textarea is focused. Did you mean the tilde key instead?

**Comment by tehphoenixz** [comment]
No, I did mean single quote, here's line from userscript extension:

![image](https://user-images.githubusercontent.com/9338660/63232554-ccaad300-c220-11e9-9ff4-9e80b7decea3.png)

Userscript header:

```
// ==UserScript==
// @name         Review Queue Helper
// @description  Keyboard shortcuts, skips accepted questions and audits (to save review quota)
// @homepage     https://github.com/samliew/SO-mod-userscripts
// @author       @samliew
// @version      1.9.3
//
// @include      https://*stackoverflow.com/review*
// @include      https://*serverfault.com/review*
// @include      https://*superuser.com/review*
// @include      https://*askubuntu.com/review*
// @include      https://*mathoverflow.net/review*
// @include      https://*.stackexchange.com/review*
//
// @include      https://*stackoverflow.com/questions/*
// @include      https://*serverfault.com/questions/*
// @include      https://*superuser.com/questions/*
// @include      https://*askubuntu.com/questions/*
// @include      https://*mathoverflow.net/questions/*
// @include      https://*.stackexchange.com/questions/*
//
// @exclude      *chat.*
// @exclude      https://stackoverflow.com/c/*
// @exclude      https://stackoverflow.blog*
//
// @grant        GM_addStyle
// ==/UserScript==
```

Screencap gif of issue:

![modboxclose](https://user-images.githubusercontent.com/9338660/63232605-53f84680-c221-11e9-8934-ed041ab5c48f.gif)

This script was the only one installed at time of recording and issue.

**Comment by tehphoenixz** [comment]
Userscript extension is Tampermonkey v4.8.41

**Comment by samliew** [comment]
Still unable to repro on Win 10 Chrome 76 and when it's the only script running, but I'll just add an ignore this particular single-quote key into the script

1a3a779

**Comment by tehphoenixz** [comment]
This may be a keyboard issue, see below gif, when I enter ' it is captured as ~ and when I enter ~ it is captured as ' in Chrome (using the keyboard tester at https://www.keyboardtester.com/). Likely this'll be a non-issue but will investigate. Using a British keyboard with OS language settings set to English (UK).

![single quote test](https://user-images.githubusercontent.com/9338660/63233529-a38e4080-c228-11e9-9f79-0e07c6d156c2.gif)

**Comment by tehphoenixz** [comment]
Click the ' key on my keyboard provides following event:

![image](https://user-images.githubusercontent.com/9338660/63233659-64acba80-c229-11e9-892f-887cd8e217d5.png)

`which`/`keyCode`: 192

Backtick (`) results in 223.

**Comment by tehphoenixz** [comment]
To clarify on last points about keyboard settings, see here another couple gifs using onscreen keyboard, this shows my actual keyboard layout, which is obviously different from the keyboard tester online:

![single quote test](https://user-images.githubusercontent.com/9338660/63234194-2e246f00-c22c-11e9-9d7c-8accc45afaea.gif)

![single quote test2](https://user-images.githubusercontent.com/9338660/63234318-aee36b00-c22c-11e9-834f-1ddc8394c4ba.gif)

**Comment by samliew** [comment]
ahh, so tilde and single quote keycodes are swapped on the UK keyboard? I better not use tilde as a shortcut then :(

**Comment by samliew** [comment]
thanks for reporting the issue, it should be fine now 👍

**Comment by tehphoenixz** [comment]
Worked a charm, thanks, I've opened a SU question to see if I can find the reason it's happening: https://superuser.com/questions/1472716/quote-is-detected-as-tilde-in-web-browsers-and-vice-versa
