### ISSUE TITLE
[Stack Exchange Dark Mode] Chat reply messages to self aren't highlighted

### ISSUE THREAD

**Issue by tehphoenixz** [samliew/SO-mod-userscripts#41]
**Describe the bug**
When a user replies to a message that you posted and you hover over it with the cursor, the highlight applied to the message replied to isn't visible.

**To Reproduce**
1. Post a message
2. Have a user reply to the message
3. Mouse over the reply
4. The message replied to isn't highlighted

**Expected behavior**
The message that was replied to should be highlighted.

**Screenshots**
In the below screenshots you can see the highlighted message from the down arrow to the left of it, cursor wasn't captured.

Expected functionality:
![image](https://user-images.githubusercontent.com/9338660/63292112-daae3180-c2bc-11e9-9e0b-2939c4163bda.png)

Actual functionality:
![image](https://user-images.githubusercontent.com/9338660/63292065-c23e1700-c2bc-11e9-99b4-6a7693b43a71.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Google Chrome
 - Version: Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
Other users replies are highlighted, only your own messages aren't.

**Comment by samliew** [comment]
Fixed, also added right yellow-green border for better visibility
