### ISSUE TITLE
Visual bug - voting options shifted lower than expected

### ISSUE THREAD

**Issue by james-work-account** [samliew/SO-mod-userscripts#43]
**Describe the bug**
I'm not sure how long this has been a thing since I haven't been on SO in a few days, but I noticed this morning that when this extension is enabled the voting arrows are shifted lower than they should be.

**To Reproduce**
1. Go to any question (as a non-mod - I'm not sure if this is a problem for mods)
2. See error (screenshot 1 vs 2)

**Expected behavior**
The voting arrows should be where they are when the extension is disabled.

**Screenshots**

1. With extension enabled
![Voting buttons are shifted down](https://i.stack.imgur.com/SEz5q.png)

2. Without extension enabled
![Voting buttons are where they should be](https://i.stack.imgur.com/YOpAp.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox Quantum
 - Version: 68.0.2 (64-bit)

**Comment by samliew** [comment]
Already fixed three days ago https://github.com/samliew/SO-mod-userscripts/commit/e31309ff48bf1d9e8e6b7bb9d9d29044e84c681a

You should probably set the tampermonkey update interval to daily or 6 hours.
