### ISSUE TITLE
Strange interaction between script and favicons

### ISSUE THREAD

**Issue by cellio** [samliew/SO-mod-userscripts#44]
In Firefox 69.0 on Windows 10 Enterprise I am seeing a bizarre interaction between [Show Deleted Messages in Chat](https://github.com/samliew/SO-mod-userscripts/blob/master/ShowDeletedMessagesInChat.user.js) and the favicon shown in certain active chat rooms (not transcripts).  When I have a tab open in rooms on Mi Yodeya (such as https://chat.stackexchange.com/rooms/468/vdibarta-bam), the favicon initially shows as the site icon and then switches to the SE generic icon after a few seconds (no more than a minute).  With the script disabled, I do not see this behavior.  I have not seen this behavior in rooms on other sites I frequent, only this one.  (I routinely use chat rooms on about half a dozen sites, so that's not an exhaustive test.)  

I have NO IDEA how this script and favicons could be interacting.  I don't see anything glaringly obvious in the source (I don't really know JS so would miss subtle).  This does not happen in Chrome on my Mac; I will try to remember to test Firefox on Mac later.  I isolated the behavior by first checking that it doesn't happen with Tampermonkey turned off, and then disabling scripts (with tab reloads) one at a time until it stopped happening.  I then disabled all scripts EXCEPT this one and reproduced the behavior.  I've cleared the browser cache; no change.

A few days ago I moved to a new Windows machine and from Win 7 to Win 10.  I never saw this behavior on the old machine.  The Firefox there might have been up to a week out of date.

I'm at a loss on how to debug this further.  (And I don't assume that Windows is blameless, since this only started on the new machine, though I have no guesses about interactions at that level.)  Any ideas?

**Comment by cellio** [comment]
This seems to be specific to Firefox 69.0.  My Mac was still on Firefox 68.0.2 where this behavior did not happen.  I then updated to 69.0 and the problem appeared with two rooms on Mi Yodeya, one mod-only and one public.  It *also* appeared with a mod-only room on Workplace but *not* a public one on the same site, and I've been unable to trigger it with other sites.  I don't understand...

**Comment by samliew** [comment]
The good news is that I'm able to repro this. The bad news is I'm almost definitely certain this is a Firefox bug.

I'll investigate possible fixes for this. Thanks for the bug report!

**Comment by cellio** [comment]
Thanks for looking into this!  It's really bizarre and it smells like a Firefox problem.  I've no idea how to identify and defend against it, and it would be totally understandable if you punted.  I hope you're able to find it.

**Comment by samliew** [comment]
Could you reinstall the script and re-test please? https://github.com/samliew/SO-mod-userscripts/blob/master/ShowDeletedMessagesInChat.user.js
