### ISSUE TITLE
css version?

### ISSUE THREAD

**Issue by wadawada** [samliew/SO-mod-userscripts#46]
I see your userscript automatically change darkness according to specific times but instant manual on/off css switch on Stylus extension gives more freedom to users instead of the need to reload all related pages to active js. It's much quicker to switch css than reloading the entire page. 
Would you consider also posting your scripts on userstyles.org ?

**Comment by samliew** [comment]
Tampermonkey also has a toggle on/off switch. No plans to support userstyles.org at the moment.
