### ISSUE TITLE
Background inverted in The Restaurant at the End of the Universe by Chat Improvements

### ISSUE THREAD

**Issue by TheHarmonicRealm** [samliew/SO-mod-userscripts#51]
**Describe the bug**
With the userscript Chat Improvements, the background image on [the Restaurant at the End of the Universe][1] and other Sci-Fi rooms is inverted. Happens in [Unix & Linux chat](https://chat.stackexchange.com/rooms/26/dev-chat), too.

**To Reproduce**
1. Go to [the Restaurant at the End of the Universe][1] with Chat Improvements on
2. Look at the bottom of the page
4. See the inverted colors

**Expected behavior**
This doesn't happen in other rooms.

**Screenshots**
It is inverted on the Restaurant:
[![][2]][2]
And Unix (bottom screenshot is the normal appearance):
[![][3]][3]
[![][4]][4]

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Firefox
 - Version: 70.0.1

**Additional context**
nice script otherwise!

  [1]: https://chat.stackexchange.com/rooms/58631/the-restaurant-at-the-end-of-the-universe
  [2]: https://i.stack.imgur.com/XeeX8.png
  [3]: https://i.stack.imgur.com/ARTtO.png
  [4]: https://i.stack.imgur.com/RyBav.png

**Comment by samliew** [comment]
Thanks, didn't know other sites have a custom bg
