### ISSUE TITLE
Low contrast date text with Chat Improvements in The Restaurant

### ISSUE THREAD

**Issue by TheHarmonicRealm** [samliew/SO-mod-userscripts#52]
**Describe the bug**
With the userscript Chat Improvements, the text color of times on messages in [the Restaurant at the End of the Universe][1] and other Sci-Fi rooms (and possibly rooms on other sites) is changed from white text on black to dark gray and unreadable text on black.

**To Reproduce**
1. Go to [the Restaurant at the End of the Universe][1] or other Sci-Fi chat room with Chat Improvements on.
2. Look at a message with a timestamp box on the transcript or in the room.

**Expected behavior**
This doesn't happen in private browsing, where the script is turned off.

**Screenshots**
In room:
[![no contrast in the room][room]][room]
In transcript:
[![no contrast in the transcript][transcript]][transcript]
Without userscript:
[![high contrast without the script][no script]][no script]

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Firefox
 - Version: 70.0.1

Thanks!

  [1]: https://chat.stackexchange.com/rooms/58631/the-restaurant-at-the-end-of-the-universe
  [room]: https://i.stack.imgur.com/iHdX8.png
  [transcript]: https://i.stack.imgur.com/o055x.png
  [no script]: https://i.stack.imgur.com/Lt2zQ.png

**Comment by samliew** [comment]
Fixed, thanks
