### ISSUE TITLE
[Dark mode] does not work on Firefox + Greasemonkey

### ISSUE THREAD

**Issue by hongshaoyang** [samliew/SO-mod-userscripts#54]
**Describe the bug**
Dark mode is not working on Firefox 72 + Greasemonkey.

    ReferenceError: GM_addStyle is not defined

is shown in the console.

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6
 - Browser: Firefox 72 + Greasemonkey 4.9

**Comment by samliew** [comment]
bummer, I've been using Tampermonkey only

**Comment by samliew** [comment]
Greasemonkey issue, they won't be fixing their GM_addStyle issue. Please install Tampermonkey instead since it's more stable.

Ref: https://github.com/greasemonkey/greasemonkey/issues/1384

**Comment by hongshaoyang** [comment]
thanks, will switch to tampermonkey! cheers.
