### ISSUE TITLE
Add how many people have selected an option in review queues

### ISSUE THREAD

**Issue by double-beep** [samliew/SO-mod-userscripts#57]
It often helps me to see other people's opinions when reviewing. I propose on hover of an action to add how many people have selected it and perhaps their names. Should perhaps look like this:

![image](https://user-images.githubusercontent.com/38133098/74365329-8781eb00-4dd6-11ea-854c-e51b486ec555.png)

**Comment by samliew** [comment]
I don't think normal users can see the result until the review has completed?

**Comment by double-beep** [comment]
Looks like you're right - should I close the issue?
