### ISSUE TITLE
Redacted shots broken if the post is deleted

### ISSUE THREAD

**Issue by DavidPostill** [samliew/SO-mod-userscripts#59]
Before:

![Screenshot - 05_03_2020 , 13_29_08](https://user-images.githubusercontent.com/7079224/75986316-c0991100-5ee5-11ea-8414-88bcfb4501bb.png)

After:

![Screenshot - 05_03_2020 , 13_29_32](https://user-images.githubusercontent.com/7079224/75986314-c0007a80-5ee5-11ea-8bb2-6f7abb02c276.png)

Ask you can see the comment author (me) has been redacted, but the author of the deleted answer (Androidquery) has not.

**Comment by samliew** [comment]
Aha, that only occurs on CW questions, since that link isn't a user profile link...
