### ISSUE TITLE
Contrast too low, especially on low-brightness settings

### ISSUE THREAD

**Issue by TheHarmonicRealm** [samliew/SO-mod-userscripts#61]
This is about [the dark mode script](https://stackapps.com/q/8053/64331).

**Is your feature request related to a problem? Please describe.**
There is some excessively low contrast in some areas. The color for a lot of the text (i.e. the one used in the body of posts and many other areas) is too dark to be very readable with the background, which is not extremely dark. Another thing: the flag icon to report comments (when not hovered over) is almost invisible.

This is not a big problem on high brightness, but, as it is a dark mode, it should be easy to read on low brightness, where it is very significant.

**Examples of low contrast**

See post body, comment, and flag icon:

[![Body of post, comment text, and flag icon are low-contrast][1]][1]

Another thing: the color of links in some areas (I noticed it when uploading a picture) is the same as the general text color:

[![Link color is no different from text][2]][2]

Thanks! This is a cool idea.

[1]: https://i.stack.imgur.com/blB44.png
[2]: https://i.stack.imgur.com/5L0eP.png

**Comment by samliew** [comment]
Should be better now, thanks.
