### ISSUE TITLE
Hover expand navigation links apparently adds a shortcut that incorrectly overrides one in Firefox

### ISSUE THREAD

**Issue by TheHarmonicRealm** [samliew/SO-mod-userscripts#62]
On post search results pages, if I press (I'm on Mac but this is probably the same issue on Windows with <kbd>ctrl</kbd>+<kbd>←</kbd>/<kbd>→</kbd>) <kbd>command</kbd>+<kbd>←</kbd>/<kbd>→</kbd>, the shortcut to go backward/forward a page on Firefox, instead of going back a page the search results page number increases or decreases by one.

**Can this be changed to only trigger if just the arrow key is pressed, so if command or control or another button is pressed at the same time the browser's command will trigger rather than the shortcut on the website?**

I'm on Firefox 74.0, which is up to date. I don't think I have seen this happen before, but its nature makes it generally not very noticeable.

Thanks!

**Comment by samliew** [comment]
Thanks for reporting, hope this resolves the issue!

**Comment by TheHarmonicRealm** [comment]
@samliew Hi! This fixes it on Windows probably, but it does not work on Mac; I just looked at [your commit][1] to fix it:

```
            // Do nothing if key modifiers were pressed
            if(evt.shiftKey || evt.ctrlKey || evt.altKey) return;
```

This does not fix it on Mac because Mac uses the command key instead. I have started [a pull request that fixes it][2]. Thank you!

[1]: https://github.com/samliew/SO-mod-userscripts/commit/cad43d02bb352e7eea9f9e4cbe62dbedf6f89118
[2]: https://github.com/samliew/SO-mod-userscripts/pull/63
