### ISSUE TITLE
Reviewing a post in H&I shows two buttons which link to different triage reviews

### ISSUE THREAD

**Issue by double-beep** [samliew/SO-mod-userscripts#64]
**To Reproduce**
1. Go to H&I.
2. Click 'Edit'.
3. Save the edits.

**Screenshots**
![image](https://user-images.githubusercontent.com/38133098/77635843-d8e7d300-6f5b-11ea-9a40-22cf2e45bdac.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80.0.3987.149

These 2 buttons link to different triage reviews.
Userscript: ReviewQueueHelper v2.6.5

**Comment by samliew** [comment]
can't repro since I'm a mod but I can guess it's because of the new flag quota counts feature.

thanks

**Comment by double-beep** [comment]
I can confirm it now works.
