### ISSUE TITLE
Post Headers & Question TOC has contrast issues with SO's new dark theme

### ISSUE THREAD

**Issue by TSchremser** [samliew/SO-mod-userscripts#66]
There are some contrast issues when using the Post Headers & Question TOC userscript with SO's new dark theme.

Parts of the post header are not readable. The background of the vote would look nicer if it were transparent.

![screenshot1](https://user-images.githubusercontent.com/58068321/78979348-f8fec100-7b1b-11ea-9e7d-fd7147a2255c.png)

At the TOC the user names are hard to read

![screenshot2](https://user-images.githubusercontent.com/58068321/78979367-03b95600-7b1c-11ea-82aa-8fc9e92a24ea.png)

**Comment by samliew** [comment]
My userscripts do not support SO's dark mode at the moment. I recommend using https://github.com/samliew/SO-mod-userscripts/blob/master/StackExchangeDarkMode.user.js

**Comment by samliew** [comment]
Updated, needs further testing https://github.com/samliew/SO-mod-userscripts/commit/31c7175f635737c6e833679bd61b733b3bce0642
