### ISSUE TITLE
Display meta flags on the main mod dashboard

### ISSUE THREAD

**Issue by JinEnMok** [samliew/SO-mod-userscripts#67]
Too often do I find myself going to meta and finding unresolved flags there that I totally wasn't aware of because I mostly visit meta for new posts only. 

Maybe it's just my problem (me being lazy), but would it be useful for anyone else to have the meta flag counter (in grey?) near the main flag counter on the main site, and vice versa?

**Comment by samliew** [comment]
Isn't this good enough?

![Screenshot_2020-04-22_170454](https://user-images.githubusercontent.com/845988/79962745-096b5000-84bb-11ea-8350-cffb8fecab50.png)

**Comment by JinEnMok** [comment]
Is that only present when there _are_ any active flags on meta? I can't see it at the moment on Literature (no meta flags).

**Comment by samliew** [comment]
Yeah, probably
