### ISSUE TITLE
Disable keyboard shortcuts for ReviewQueueHelper

### ISSUE THREAD

**Issue by NicoHaase** [samliew/SO-mod-userscripts#69]
Working in review queues with your userscript is much more comfortable due to the quicklinks. But from time to time, when writing a comment that contains numbers, one of the quicklinks is randomly triggered - I haven't found out a precise pattern besides the numbers. It would be cool if there was any way to disable the keyboard shortcuts, such that this happens no more.

**Comment by samliew** [comment]
Thanks, should be fine now (reinstall or update userscript)
