### ISSUE TITLE
Hyperlinks in comments broken when filtering by comments

### ISSUE THREAD

**Issue by rjrudman** [samliew/SO-mod-userscripts#7]
**Describe the bug**
A bit difficult to describe, screenshots are more useful.

Here's what the flagged comment looks like when filtering to 'not relevant' comments:

![image](https://user-images.githubusercontent.com/709585/43522557-158267b2-95dd-11e8-8496-88c631b41e5b.png)

And editing it:

![image](https://user-images.githubusercontent.com/709585/43522608-3105f6c0-95dd-11e8-82a8-1b6aa98cf195.png)

That's not the actual content of the comment, however. Visiting the post, the comment looks like this:

![image](https://user-images.githubusercontent.com/709585/43522642-4d05ac30-95dd-11e8-943c-f393f5344f35.png)

This has suspiciously happened with the re-naming of comment flags, so perhaps that's a reason.

This happens for every comment with a link in it

**Comment by samliew** [comment]
https://github.com/samliew/SO-mod-userscripts/commit/fdb50f6b7c96915eab022a5f6700eaa647ceebd5

**Comment by rjrudman** [comment]
Thanks!
