### ISSUE TITLE
ReferenceError: $ is not defined, using chat imprevements

### ISSUE THREAD

**Issue by braiam** [samliew/SO-mod-userscripts#76]
**Describe the bug**
Installing Chat Improvements in Firefox 77.0; GM 4.9

```Script error in [Greasemonkey script raw.githubusercontent.com/Chat Improvements; version 2.18.2]:
ReferenceError: $ is not defined
```

**To Reproduce**
1. Install the extension
2. Refresh chat

**Expected behavior**
Awesomesauce for SE chat.

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Browser Firefox
 - Version 77.0

**Comment by samliew** [comment]
Please try Tampermonkey. It's working on it for me on both FF and Chrome.
