### ISSUE TITLE
ReduceClutter - The plus/minus icons to show dupe changes in the revision page are incorrectly positioned for me

### ISSUE THREAD

**Issue by Tyler-H** [samliew/SO-mod-userscripts#88]
**Describe the bug**
In ReduceClutter 1.24.1, the plus/minus icons to show dupe changes in the revision page are incorrectly positioned for me.

**To Reproduce:**
1. Install ReduceClutter 1.24.1 into Firefox
2. In Firefox, navigate to https://stackoverflow.com/posts/16086086/revisions
3. Look at the top left of the page:
4. See screenshot below

**Expected behavior:**
I expect the +/- icons to show inline just before the rest of the bullet point.

**Screenshots:**
![Annotation 2020-09-01 104704](https://user-images.githubusercontent.com/206492/91866953-15250b00-ec41-11ea-9477-607e41cd2100.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 79.0

**Additional context**
According to a screenshot from Sam it should look like this:
![Image from https://meta.stackoverflow.com/a/400818/2756409](https://i.stack.imgur.com/I7Q1l.png)

I get this malformed layout in private browsing as well (tested to ensure it wasn't some weird profile-based thing such as dark mode, etc.).

**Comment by samliew** [comment]
Fixed, thanks. Please update.
