### ISSUE TITLE
Update UserReviewBanHelper to adjust action names

### ISSUE THREAD

**Issue by mjpieters** [samliew/SO-mod-userscripts#91]
*This was promoted by a [Meta post](https://meta.stackoverflow.com/questions/402569/review-suspended-message-unsalvageable-change-to-flag).*

The Triage review queue actions [have been updated](https://meta.stackoverflow.com/questions/402478/announcing-tweaks-to-the-triage-queue) but the script canned messages still use the old language.

**Comment by makyen** [comment]
Sam, just an FYI: They also re-changed "Approve" back to "Looks OK". You'll almost certainly notice that when you're looking at updating the script again. I only mention it because I noticed the change to "Approve" in the most recent script update. Fortunately, SE changed if back to "Looks OK", but, unfortunately, they did so just after you put in the effort to update the script to "Approve". :;

**Comment by ppwater01** [comment]
> Choose the "Unsalvageable" action for questions that should be closed or can only be improved or clarified by the question-asker. The "Needs community edit" action should only be used when other community users (like yourself) are able to improve an answerable question with editing or formatting. When in doubt, use the Skip action. Being suspended can be a frustrating experience, but your help in moderation is still important. In the meantime, you can refer to Getting banned from Triage reviews and How does the Triage queue work? for more information, and revisit your recent reviews to see if you could have taken a different action instead.

this message have to be changed to 
> Choose the "Flag" action for questions that should be closed or can only be improved or clarified by the question-asker. The "Needs community edit" action should only be used when other community users (like yourself) are able to improve an answerable question with editing or formatting. When in doubt, use the Skip action. Being suspended can be a frustrating experience, but your help in moderation is still important. In the meantime, you can refer to Getting banned from Triage reviews and How does the Triage queue work? for more information, and revisit your recent reviews to see if you could have taken a different action instead.
