### ISSUE TITLE
ReduceClutter - ServerFault top bar expanded due to malformed image

### ISSUE THREAD

**Issue by Tyler-H** [samliew/SO-mod-userscripts#97]
**Describe the bug**
With the ReduceClutter script activated, the top bar on https://serverfault.com is too large and shows a blank placeholder for the image there, but at a larger size than should be shown (I think).

**To Reproduce**
1. Enable ReduceClutter
2. Go to Server Fault
3. See that the site header is larger than expected

**Expected behavior**
The site header should be normal height (70px).

**Screenshots**
![image](https://user-images.githubusercontent.com/206492/114602110-3bde0200-9c64-11eb-9c27-4fdab26b12aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 87.0
 - Version: Reduce Clutter v1.29.1

No other sites seem to be affected by this that I have noticed.

**Comment by samliew** [comment]
Unable to repro, might be a promotional image that was previously displayed at that location.
